export function numberToOrdinal(n) {
  const ordinals = [
    "primeiro",
    "segundo",
    "terceiro",
    "quarto",
    "quinto",
    "sexto",
    "sétimo",
    "oitavo",
    "nono",
    "décimo",
    "décimo primeiro",
    "décimo segundo",
    "décimo terceiro",
    "décimo quarto",
    "décimo quinto",
    "décimo sexto",
    "décimo sétimo",
    "décimo oitavo",
    "décimo nono",
    "vigésimo",
    "vigésimo primeiro",
    "vigésimo segundo",
    "vigésimo terceiro",
    "vigésimo quarto",
    "vigésimo quinto",
    "vigésimo sexto",
    "vigésimo sétimo",
    "vigésimo oitavo",
    "vigésimo nono",
    "trigésimo",
    "trigésimo primeiro",
    "trigésimo segundo",
    "trigésimo terceiro",
    "trigésimo quarto",
    "trigésimo quinto",
    "trigésimo sexto",
    "trigésimo sétimo",
    "trigésimo oitavo",
    "trigésimo nono",
    "quadragésimo",
    "quadragésimo primeiro",
    "quadragésimo segundo",
    "quadragésimo terceiro",
    "quadragésimo quarto",
    "quadragésimo quinto",
    "quadragésimo sexto",
    "quadragésimo sétimo",
    "quadragésimo oitavo",
    "quadragésimo nono",
    "quinquagésimo",
    "quinquagésimo primeiro",
    "quinquagésimo segundo",
    "quinquagésimo terceiro",
    "quinquagésimo quarto",
    "quinquagésimo quinto",
    "quinquagésimo sexto",
    "quinquagésimo sétimo",
    "quinquagésimo oitavo",
    "quinquagésimo nono",
    "sexagésimo",
    "sexagésimo primeiro",
    "sexagésimo segundo",
    "sexagésimo terceiro",
    "sexagésimo quarto",
    "sexagésimo quinto",
    "sexagésimo sexto",
    "sexagésimo sétimo",
    "sexagésimo oitavo",
    "sexagésimo nono",
    "septuagésimo",
    "septuagésimo primeiro",
    "septuagésimo segundo",
    "septuagésimo terceiro",
    "septuagésimo quarto",
    "septuagésimo quinto",
    "septuagésimo sexto",
    "septuagésimo sétimo",
    "septuagésimo oitavo",
    "septuagésimo nono",
    "octogésimo",
    "octogésimo primeiro",
    "octogésimo segundo",
    "octogésimo terceiro",
    "octogésimo quarto",
    "octogésimo quinto",
    "octogésimo sexto",
    "octogésimo sétimo",
    "octogésimo oitavo",
    "octogésimo nono",
    "nonagésimo",
    "nonagésimo primeiro",
    "nonagésimo segundo",
    "nonagésimo terceiro",
    "nonagésimo quarto",
    "nonagésimo quinto",
    "nonagésimo sexto",
    "nonagésimo sétimo",
    "nonagésimo oitavo",
    "nonagésimo nono",
  ];

  if (n < 1 || n > 99) {
    throw new Error("Número fora do intervalo suportado (1-99)");
  }

  return ordinals[n - 1];
}
